/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as ProtectedSupportRouteImport } from './routes/_protected/support'
import { Route as ProtectedFeedbackRouteImport } from './routes/_protected/feedback'
import { Route as ProtectedCategoriesRouteImport } from './routes/_protected/categories'
import { Route as ProtectedSettingsRouteRouteImport } from './routes/_protected/settings/route'
import { Route as ProtectedPlaygroundRouteRouteImport } from './routes/_protected/playground/route'
import { Route as ProtectedDocsRouteRouteImport } from './routes/_protected/docs/route'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as ProtectedVendorsIndexRouteImport } from './routes/_protected/vendors/index'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedStoresIndexRouteImport } from './routes/_protected/stores/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSessionsIndexRouteImport } from './routes/_protected/sessions/index'
import { Route as ProtectedPlaygroundIndexRouteImport } from './routes/_protected/playground/index'
import { Route as ProtectedDocsIndexRouteImport } from './routes/_protected/docs/index'
import { Route as ProtectedUsersSelectRouteImport } from './routes/_protected/users/select'
import { Route as ProtectedStoresStoreIdRouteImport } from './routes/_protected/stores/$storeId'
import { Route as ProtectedSettingsTeamRouteImport } from './routes/_protected/settings/team'
import { Route as ProtectedSettingsSessionsRouteImport } from './routes/_protected/settings/sessions'
import { Route as ProtectedSettingsSecurityRouteImport } from './routes/_protected/settings/security'
import { Route as ProtectedSettingsProfileRouteImport } from './routes/_protected/settings/profile'
import { Route as ProtectedSettingsLimitsRouteImport } from './routes/_protected/settings/limits'
import { Route as ProtectedSettingsGeneralRouteImport } from './routes/_protected/settings/general'
import { Route as ProtectedSettingsBillingRouteImport } from './routes/_protected/settings/billing'
import { Route as ProtectedPlaygroundHistoryRouteImport } from './routes/_protected/playground/history'
import { Route as ProtectedPlaygroundFavoritesRouteImport } from './routes/_protected/playground/favorites'
import { Route as ProtectedDocsTutorialsRouteImport } from './routes/_protected/docs/tutorials'
import { Route as ProtectedDocsIntroductionRouteImport } from './routes/_protected/docs/introduction'
import { Route as ProtectedDocsGetStartedRouteImport } from './routes/_protected/docs/get-started'
import { Route as ProtectedDocsChangelogRouteImport } from './routes/_protected/docs/changelog'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedSupportRoute = ProtectedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFeedbackRoute = ProtectedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCategoriesRoute = ProtectedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRouteRoute = ProtectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPlaygroundRouteRoute =
  ProtectedPlaygroundRouteRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDocsRouteRoute = ProtectedDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedVendorsIndexRoute = ProtectedVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStoresIndexRoute = ProtectedStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSessionsIndexRoute = ProtectedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPlaygroundIndexRoute =
  ProtectedPlaygroundIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedPlaygroundRouteRoute,
  } as any)
const ProtectedDocsIndexRoute = ProtectedDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDocsRouteRoute,
} as any)
const ProtectedUsersSelectRoute = ProtectedUsersSelectRouteImport.update({
  id: '/users/select',
  path: '/users/select',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStoresStoreIdRoute = ProtectedStoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsTeamRoute = ProtectedSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSettingsSessionsRoute =
  ProtectedSettingsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsSecurityRoute =
  ProtectedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsProfileRoute =
  ProtectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsLimitsRoute = ProtectedSettingsLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => ProtectedSettingsRouteRoute,
} as any)
const ProtectedSettingsGeneralRoute =
  ProtectedSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedSettingsBillingRoute =
  ProtectedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => ProtectedSettingsRouteRoute,
  } as any)
const ProtectedPlaygroundHistoryRoute =
  ProtectedPlaygroundHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedPlaygroundRouteRoute,
  } as any)
const ProtectedPlaygroundFavoritesRoute =
  ProtectedPlaygroundFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => ProtectedPlaygroundRouteRoute,
  } as any)
const ProtectedDocsTutorialsRoute = ProtectedDocsTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => ProtectedDocsRouteRoute,
} as any)
const ProtectedDocsIntroductionRoute =
  ProtectedDocsIntroductionRouteImport.update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => ProtectedDocsRouteRoute,
  } as any)
const ProtectedDocsGetStartedRoute = ProtectedDocsGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => ProtectedDocsRouteRoute,
} as any)
const ProtectedDocsChangelogRoute = ProtectedDocsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => ProtectedDocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/docs': typeof ProtectedDocsRouteRouteWithChildren
  '/playground': typeof ProtectedPlaygroundRouteRouteWithChildren
  '/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/categories': typeof ProtectedCategoriesRoute
  '/feedback': typeof ProtectedFeedbackRoute
  '/support': typeof ProtectedSupportRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/docs/changelog': typeof ProtectedDocsChangelogRoute
  '/docs/get-started': typeof ProtectedDocsGetStartedRoute
  '/docs/introduction': typeof ProtectedDocsIntroductionRoute
  '/docs/tutorials': typeof ProtectedDocsTutorialsRoute
  '/playground/favorites': typeof ProtectedPlaygroundFavoritesRoute
  '/playground/history': typeof ProtectedPlaygroundHistoryRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/limits': typeof ProtectedSettingsLimitsRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/settings/sessions': typeof ProtectedSettingsSessionsRoute
  '/settings/team': typeof ProtectedSettingsTeamRoute
  '/stores/$storeId': typeof ProtectedStoresStoreIdRoute
  '/users/select': typeof ProtectedUsersSelectRoute
  '/docs/': typeof ProtectedDocsIndexRoute
  '/playground/': typeof ProtectedPlaygroundIndexRoute
  '/sessions/': typeof ProtectedSessionsIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/stores/': typeof ProtectedStoresIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
  '/vendors/': typeof ProtectedVendorsIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/categories': typeof ProtectedCategoriesRoute
  '/feedback': typeof ProtectedFeedbackRoute
  '/support': typeof ProtectedSupportRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof ProtectedIndexRoute
  '/docs/changelog': typeof ProtectedDocsChangelogRoute
  '/docs/get-started': typeof ProtectedDocsGetStartedRoute
  '/docs/introduction': typeof ProtectedDocsIntroductionRoute
  '/docs/tutorials': typeof ProtectedDocsTutorialsRoute
  '/playground/favorites': typeof ProtectedPlaygroundFavoritesRoute
  '/playground/history': typeof ProtectedPlaygroundHistoryRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/limits': typeof ProtectedSettingsLimitsRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/settings/sessions': typeof ProtectedSettingsSessionsRoute
  '/settings/team': typeof ProtectedSettingsTeamRoute
  '/stores/$storeId': typeof ProtectedStoresStoreIdRoute
  '/users/select': typeof ProtectedUsersSelectRoute
  '/docs': typeof ProtectedDocsIndexRoute
  '/playground': typeof ProtectedPlaygroundIndexRoute
  '/sessions': typeof ProtectedSessionsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/stores': typeof ProtectedStoresIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/vendors': typeof ProtectedVendorsIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected/docs': typeof ProtectedDocsRouteRouteWithChildren
  '/_protected/playground': typeof ProtectedPlaygroundRouteRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteRouteWithChildren
  '/_protected/categories': typeof ProtectedCategoriesRoute
  '/_protected/feedback': typeof ProtectedFeedbackRoute
  '/_protected/support': typeof ProtectedSupportRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/docs/changelog': typeof ProtectedDocsChangelogRoute
  '/_protected/docs/get-started': typeof ProtectedDocsGetStartedRoute
  '/_protected/docs/introduction': typeof ProtectedDocsIntroductionRoute
  '/_protected/docs/tutorials': typeof ProtectedDocsTutorialsRoute
  '/_protected/playground/favorites': typeof ProtectedPlaygroundFavoritesRoute
  '/_protected/playground/history': typeof ProtectedPlaygroundHistoryRoute
  '/_protected/settings/billing': typeof ProtectedSettingsBillingRoute
  '/_protected/settings/general': typeof ProtectedSettingsGeneralRoute
  '/_protected/settings/limits': typeof ProtectedSettingsLimitsRoute
  '/_protected/settings/profile': typeof ProtectedSettingsProfileRoute
  '/_protected/settings/security': typeof ProtectedSettingsSecurityRoute
  '/_protected/settings/sessions': typeof ProtectedSettingsSessionsRoute
  '/_protected/settings/team': typeof ProtectedSettingsTeamRoute
  '/_protected/stores/$storeId': typeof ProtectedStoresStoreIdRoute
  '/_protected/users/select': typeof ProtectedUsersSelectRoute
  '/_protected/docs/': typeof ProtectedDocsIndexRoute
  '/_protected/playground/': typeof ProtectedPlaygroundIndexRoute
  '/_protected/sessions/': typeof ProtectedSessionsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/stores/': typeof ProtectedStoresIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/vendors/': typeof ProtectedVendorsIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/playground'
    | '/settings'
    | '/categories'
    | '/feedback'
    | '/support'
    | '/auth/sign-up'
    | '/docs/changelog'
    | '/docs/get-started'
    | '/docs/introduction'
    | '/docs/tutorials'
    | '/playground/favorites'
    | '/playground/history'
    | '/settings/billing'
    | '/settings/general'
    | '/settings/limits'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/team'
    | '/stores/$storeId'
    | '/users/select'
    | '/docs/'
    | '/playground/'
    | '/sessions/'
    | '/settings/'
    | '/stores/'
    | '/users/'
    | '/vendors/'
    | '/auth/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/categories'
    | '/feedback'
    | '/support'
    | '/auth/sign-up'
    | '/'
    | '/docs/changelog'
    | '/docs/get-started'
    | '/docs/introduction'
    | '/docs/tutorials'
    | '/playground/favorites'
    | '/playground/history'
    | '/settings/billing'
    | '/settings/general'
    | '/settings/limits'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/team'
    | '/stores/$storeId'
    | '/users/select'
    | '/docs'
    | '/playground'
    | '/sessions'
    | '/settings'
    | '/stores'
    | '/users'
    | '/vendors'
    | '/auth/sign-in'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/docs'
    | '/_protected/playground'
    | '/_protected/settings'
    | '/_protected/categories'
    | '/_protected/feedback'
    | '/_protected/support'
    | '/auth/sign-up'
    | '/_protected/'
    | '/_protected/docs/changelog'
    | '/_protected/docs/get-started'
    | '/_protected/docs/introduction'
    | '/_protected/docs/tutorials'
    | '/_protected/playground/favorites'
    | '/_protected/playground/history'
    | '/_protected/settings/billing'
    | '/_protected/settings/general'
    | '/_protected/settings/limits'
    | '/_protected/settings/profile'
    | '/_protected/settings/security'
    | '/_protected/settings/sessions'
    | '/_protected/settings/team'
    | '/_protected/stores/$storeId'
    | '/_protected/users/select'
    | '/_protected/docs/'
    | '/_protected/playground/'
    | '/_protected/sessions/'
    | '/_protected/settings/'
    | '/_protected/stores/'
    | '/_protected/users/'
    | '/_protected/vendors/'
    | '/auth/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/support': {
      id: '/_protected/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ProtectedSupportRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/feedback': {
      id: '/_protected/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof ProtectedFeedbackRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/categories': {
      id: '/_protected/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof ProtectedCategoriesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/playground': {
      id: '/_protected/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof ProtectedPlaygroundRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/docs': {
      id: '/_protected/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ProtectedDocsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/vendors/': {
      id: '/_protected/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof ProtectedVendorsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stores/': {
      id: '/_protected/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof ProtectedStoresIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/sessions/': {
      id: '/_protected/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof ProtectedSessionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/playground/': {
      id: '/_protected/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof ProtectedPlaygroundIndexRouteImport
      parentRoute: typeof ProtectedPlaygroundRouteRoute
    }
    '/_protected/docs/': {
      id: '/_protected/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof ProtectedDocsIndexRouteImport
      parentRoute: typeof ProtectedDocsRouteRoute
    }
    '/_protected/users/select': {
      id: '/_protected/users/select'
      path: '/users/select'
      fullPath: '/users/select'
      preLoaderRoute: typeof ProtectedUsersSelectRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/stores/$storeId': {
      id: '/_protected/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof ProtectedStoresStoreIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/team': {
      id: '/_protected/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof ProtectedSettingsTeamRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/sessions': {
      id: '/_protected/settings/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof ProtectedSettingsSessionsRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/security': {
      id: '/_protected/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof ProtectedSettingsSecurityRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/profile': {
      id: '/_protected/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedSettingsProfileRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/limits': {
      id: '/_protected/settings/limits'
      path: '/limits'
      fullPath: '/settings/limits'
      preLoaderRoute: typeof ProtectedSettingsLimitsRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/general': {
      id: '/_protected/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ProtectedSettingsGeneralRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/settings/billing': {
      id: '/_protected/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof ProtectedSettingsBillingRouteImport
      parentRoute: typeof ProtectedSettingsRouteRoute
    }
    '/_protected/playground/history': {
      id: '/_protected/playground/history'
      path: '/history'
      fullPath: '/playground/history'
      preLoaderRoute: typeof ProtectedPlaygroundHistoryRouteImport
      parentRoute: typeof ProtectedPlaygroundRouteRoute
    }
    '/_protected/playground/favorites': {
      id: '/_protected/playground/favorites'
      path: '/favorites'
      fullPath: '/playground/favorites'
      preLoaderRoute: typeof ProtectedPlaygroundFavoritesRouteImport
      parentRoute: typeof ProtectedPlaygroundRouteRoute
    }
    '/_protected/docs/tutorials': {
      id: '/_protected/docs/tutorials'
      path: '/tutorials'
      fullPath: '/docs/tutorials'
      preLoaderRoute: typeof ProtectedDocsTutorialsRouteImport
      parentRoute: typeof ProtectedDocsRouteRoute
    }
    '/_protected/docs/introduction': {
      id: '/_protected/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof ProtectedDocsIntroductionRouteImport
      parentRoute: typeof ProtectedDocsRouteRoute
    }
    '/_protected/docs/get-started': {
      id: '/_protected/docs/get-started'
      path: '/get-started'
      fullPath: '/docs/get-started'
      preLoaderRoute: typeof ProtectedDocsGetStartedRouteImport
      parentRoute: typeof ProtectedDocsRouteRoute
    }
    '/_protected/docs/changelog': {
      id: '/_protected/docs/changelog'
      path: '/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof ProtectedDocsChangelogRouteImport
      parentRoute: typeof ProtectedDocsRouteRoute
    }
  }
}

interface ProtectedDocsRouteRouteChildren {
  ProtectedDocsChangelogRoute: typeof ProtectedDocsChangelogRoute
  ProtectedDocsGetStartedRoute: typeof ProtectedDocsGetStartedRoute
  ProtectedDocsIntroductionRoute: typeof ProtectedDocsIntroductionRoute
  ProtectedDocsTutorialsRoute: typeof ProtectedDocsTutorialsRoute
  ProtectedDocsIndexRoute: typeof ProtectedDocsIndexRoute
}

const ProtectedDocsRouteRouteChildren: ProtectedDocsRouteRouteChildren = {
  ProtectedDocsChangelogRoute: ProtectedDocsChangelogRoute,
  ProtectedDocsGetStartedRoute: ProtectedDocsGetStartedRoute,
  ProtectedDocsIntroductionRoute: ProtectedDocsIntroductionRoute,
  ProtectedDocsTutorialsRoute: ProtectedDocsTutorialsRoute,
  ProtectedDocsIndexRoute: ProtectedDocsIndexRoute,
}

const ProtectedDocsRouteRouteWithChildren =
  ProtectedDocsRouteRoute._addFileChildren(ProtectedDocsRouteRouteChildren)

interface ProtectedPlaygroundRouteRouteChildren {
  ProtectedPlaygroundFavoritesRoute: typeof ProtectedPlaygroundFavoritesRoute
  ProtectedPlaygroundHistoryRoute: typeof ProtectedPlaygroundHistoryRoute
  ProtectedPlaygroundIndexRoute: typeof ProtectedPlaygroundIndexRoute
}

const ProtectedPlaygroundRouteRouteChildren: ProtectedPlaygroundRouteRouteChildren =
  {
    ProtectedPlaygroundFavoritesRoute: ProtectedPlaygroundFavoritesRoute,
    ProtectedPlaygroundHistoryRoute: ProtectedPlaygroundHistoryRoute,
    ProtectedPlaygroundIndexRoute: ProtectedPlaygroundIndexRoute,
  }

const ProtectedPlaygroundRouteRouteWithChildren =
  ProtectedPlaygroundRouteRoute._addFileChildren(
    ProtectedPlaygroundRouteRouteChildren,
  )

interface ProtectedSettingsRouteRouteChildren {
  ProtectedSettingsBillingRoute: typeof ProtectedSettingsBillingRoute
  ProtectedSettingsGeneralRoute: typeof ProtectedSettingsGeneralRoute
  ProtectedSettingsLimitsRoute: typeof ProtectedSettingsLimitsRoute
  ProtectedSettingsProfileRoute: typeof ProtectedSettingsProfileRoute
  ProtectedSettingsSecurityRoute: typeof ProtectedSettingsSecurityRoute
  ProtectedSettingsSessionsRoute: typeof ProtectedSettingsSessionsRoute
  ProtectedSettingsTeamRoute: typeof ProtectedSettingsTeamRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteRouteChildren: ProtectedSettingsRouteRouteChildren =
  {
    ProtectedSettingsBillingRoute: ProtectedSettingsBillingRoute,
    ProtectedSettingsGeneralRoute: ProtectedSettingsGeneralRoute,
    ProtectedSettingsLimitsRoute: ProtectedSettingsLimitsRoute,
    ProtectedSettingsProfileRoute: ProtectedSettingsProfileRoute,
    ProtectedSettingsSecurityRoute: ProtectedSettingsSecurityRoute,
    ProtectedSettingsSessionsRoute: ProtectedSettingsSessionsRoute,
    ProtectedSettingsTeamRoute: ProtectedSettingsTeamRoute,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  }

const ProtectedSettingsRouteRouteWithChildren =
  ProtectedSettingsRouteRoute._addFileChildren(
    ProtectedSettingsRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedDocsRouteRoute: typeof ProtectedDocsRouteRouteWithChildren
  ProtectedPlaygroundRouteRoute: typeof ProtectedPlaygroundRouteRouteWithChildren
  ProtectedSettingsRouteRoute: typeof ProtectedSettingsRouteRouteWithChildren
  ProtectedCategoriesRoute: typeof ProtectedCategoriesRoute
  ProtectedFeedbackRoute: typeof ProtectedFeedbackRoute
  ProtectedSupportRoute: typeof ProtectedSupportRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedStoresStoreIdRoute: typeof ProtectedStoresStoreIdRoute
  ProtectedUsersSelectRoute: typeof ProtectedUsersSelectRoute
  ProtectedSessionsIndexRoute: typeof ProtectedSessionsIndexRoute
  ProtectedStoresIndexRoute: typeof ProtectedStoresIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedVendorsIndexRoute: typeof ProtectedVendorsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDocsRouteRoute: ProtectedDocsRouteRouteWithChildren,
  ProtectedPlaygroundRouteRoute: ProtectedPlaygroundRouteRouteWithChildren,
  ProtectedSettingsRouteRoute: ProtectedSettingsRouteRouteWithChildren,
  ProtectedCategoriesRoute: ProtectedCategoriesRoute,
  ProtectedFeedbackRoute: ProtectedFeedbackRoute,
  ProtectedSupportRoute: ProtectedSupportRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedStoresStoreIdRoute: ProtectedStoresStoreIdRoute,
  ProtectedUsersSelectRoute: ProtectedUsersSelectRoute,
  ProtectedSessionsIndexRoute: ProtectedSessionsIndexRoute,
  ProtectedStoresIndexRoute: ProtectedStoresIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedVendorsIndexRoute: ProtectedVendorsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
